const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')

const userRoutes = require('./routes/userRoutes')
const productRoutes = require('./routes/productRoutes')
const voucherRoutes = require('./routes/voucherRoutes')
const bannerRoutes = require('./routes/bannerRoutes')
const addressRoutes = require('./routes/addressRoutes')
const cartRoutes = require('./routes/cartRoutes')
const chatRoutes = require('./routes/chatRoutes')
const customerRoutes = require('./routes/customerRoutes')
const employeeRoutes = require('./routes/employeeRoutes')
const evaluateRoutes = require('./routes/evaluateRoutes')
const ingredientRoutes = require('./routes/IngredientRoutes')
const billImpoortRoutes = require('./routes/billImportRoutes')
const tableRoutes = require('./routes/tableRoutes')
const billSellRoutes = require('./routes/billSellRouter')
const orderRoutes = require('./routes/orderRoutes')
const reviewRoutes = require('./routes/reviewRoutes')

const app = express()
const port = 3000

app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.use('/user', userRoutes)
app.use('/product', productRoutes)
app.use('/voucher', voucherRoutes)
app.use('/banner', bannerRoutes)
app.use('/address', addressRoutes)
app.use('/cart', cartRoutes)
app.use('/chat', chatRoutes)
app.use('/customer', customerRoutes)
app.use('/employee', employeeRoutes)
app.use('/evaluate', evaluateRoutes)
app.use('/ingredient', ingredientRoutes)
app.use('/bill-import', billImpoortRoutes)
app.use('/table', tableRoutes)
app.use('/bill-sell', billSellRoutes)
app.use('/order', orderRoutes)
app.use('/review', reviewRoutes)

app.listen(port, () => {
    console.log(`Server is running on port ${port}`)
})
